name: Build
  on:
    workflow_dispatch:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
    
jobs:
  build:
    name: Build and test
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Show current version of Xcode
      run: xcodebuild -version
