name: Build
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Install Theos
      uses: Randomblock1/theos-action@v1.4
        with:
          # Where to install Theos
          theos-dir: # optional, default is ${{ github.workspace }}/theos
          # Where to clone Theos from (git URL)
          theos-src: # optional, default is https://github.com/theos/theos
          # Where to clone the iOS SDKs from (GitHub repository URL)
          theos-sdks: # optional, default is https://github.com/theos/sdks
          # Which branch to clone from SDK repo
          theos-sdks-branch: # optional, default is master
          # Whether to enable Orion, which adds support for Swift tweaks
          orion: # optional, default is false
    - name: Run build script
      run: ./build.sh
